### ISSUE TITLE
Question: how to run without confirmation

### ISSUE THREAD

**Issue by ftrojahn** [sypets/cal2calendarize#5]
Hi Sylke,

we are trying to script our migration using 'vendor/bin/typo3cms cal2calendarize:migrateCalPlugins -n'.

In 0f814c49a2d5697db639b0283c62ce0745501e2f there is:

> Additionally, make it necessary to confirm the checking. (This can be prevented by supplying the -n option)

But adding "-n" seems to not to run the migration?

If this is an option:  I would suggest to do it like in ext:migration by using "--dry-run 0" vs. "--dry-run 1"

Thanx!

**Comment by sypets** [comment]
@ftrojahn

Thanks for checking out the extension and for your feedback.

Please note that this is an experimental version. I did use the extension myself to migrate but it has not officially been published. However if other people show interest in it, I migtht make it ready for publishing and add some more checks. 

Anyway, please make backup before you migrate and be aware this might not migrate everything as you need it. The mapping in the plugins was a bit difficult. 

---

About the options:

In general  I try to use the conventions as done in the TYPO3 core - same as the other commands based on Symfony command.

Some options are already built in in the and some are common conventions, usually

* `-n` for no interaction
* and `--dry-run` for dry-run

so I would like to use `--dry-run` for dry run and not passing the option means do not do dry-run to stick with the conventions.

But, the behaviour may currently be buggy, I would have to check.

**Comment by ftrojahn** [comment]
@sypets thanx for your fast reply.

We are in the process of preparing a "biginstallation" migration with several hundred domains, facing the usual problems
like mentioned in the "biginstallations" core issue. So, e.g. patching ext:calendarize is needed anyway. If we have some
contributions for cal2calendarize, we will make PR accordingly.

When using "-n" didn't show the same output as entering "y" at the prompt, I assumed it did not work. But, maybe there simply was nothing to migrate anymore. I'll check again and report back.

**Comment by ftrojahn** [comment]
Just re-tested: using "-n" did the same as entering "n" at the prompt.

**Comment by sypets** [comment]
I can confirm that the `-n` has no effect. I am pushing a fix.
